### ISSUE TITLE
Create User Stories for Onboarding

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#2]
User Story 1

Go to dao.hypha.earth, click on register. 
We don't know why. We don't care. 

User Story 2

I am inviting members to my account
I need to pay some Hypha tokens (?) for each invite
Members click on the invite link and get invited and onboarded into the wallet

User Story 3

I have a Telos account and want to check out Hypha DAO

User Story 4

I want to join a specific DAO but don’t have an invite - I am not sure we allow this - maybe we should require invites? On the other hand some DAOs may want to be open?

We can add user stories here, and the solutions (proposed) in the comments.

**Comment by n13** [comment]
User story 2

1. Invite member button somewhere prominent
2. invite link / QR code to send to a new member - maybe just invite link since these days nobody really sends QR codes in messages
3. Onboarding like User story 2 once in the wallet

There will need to be some form of payment for onboarding members, to prevent sybil attatcks, e.g. I could create a new DAO myself, then onboard and sell off 1M user accounts with invite links if it was free. There needs to be a small fee, probably in Hypha tokens?

**Comment by n13** [comment]
User Story 3

1. Exsiting Telos users - this case handled on page one create account / login - at the bottom there is a text link
2. Text link text: "I have an existing Telos blockchain account" OR "I have an existing EOS blockchain account"
3. Login with Anchor, Account create flow - this will be as-is, @luigicarlini1988 is currently designing this flow on the website and it will be the same with wallet. We could allow people to switch to the wallet from their anchor wallet eventually (make that really easy - but they will likely still have to copy their private key out of their existing wallet and import it into the Hypha wallet)

This text self selects people who have this, the word blockchain is there for ppl who don't know what Telos or EOS is.
