### ISSUE TITLE
Authentication bug

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#52]
**Describe the bug**
Keep seeing this in the console: 
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: add(_$_OnAuthenticatedDataChanged) was called without a registered event handler.
Make sure to register a handler via on<_$_OnAuthenticatedDataChanged>((event, emit) {...})
#0      Bloc.add.<anonymous closure>
bloc.dart:90
#1      Bloc.add
bloc.dart:96
#2      new AuthenticationBloc.<anonymous closure>
authentication_bloc.dart:39
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
```

**To Reproduce**
Any time I start the app

**Current behavior**
A crash happens

**Expected behavior**
Implement the _OnAuthenticatedDataChanged handler

** Notes ***
As an aside, that's another bug due to generated code. 

I do not like generated code. Things are very simple with event handlers - just implement them, they work. We never get an issue like this. This only happens due to the convoluted nature of the generated code, normally, this isn't even a possible bug. It would be caught by the compiler.

**Comment by gguijarro-c-chwy** [comment]
`Unhandled Exception: Bad state: add(_$_OnAuthenticatedDataChanged) was called without a registered event handler.` 

^^ This is all you need to see where the issue is. This is again nothing to do with code generation, This can also happen when we create models without code generation. 

What is wrong is that we call this event `onUserProfileDataChanged` but in the bloc we dont listen for this event 

on<_OnAuthenticatedDataChanged>(_onAuthenticatedDataChanged); -> This line of code is missing. 

This was an issue i added with the recent auth refactor.

**Comment by gguijarro-c-chwy** [comment]
https://github.com/hypha-dao/hypha_wallet/pull/59
